DROP TABLE IF EXISTS TX_TRANSACTION;
DROP TABLE IF EXISTS INSTRUMENT;
DROP TABLE IF EXISTS PARTY;

CREATE TABLE PARTY (
    PARTY_ID NUMBER PRIMARY KEY,
    PARTY_NAME VARCHAR2(200) NOT NULL,
    PARTY_TYPE VARCHAR2(30) NOT NULL,
    TAX_ID VARCHAR2(30),
    COUNTRY VARCHAR2(3),
    SECTOR VARCHAR2(50),
    RATING VARCHAR2(10),
    IS_ACTIVE NUMBER(1) NOT NULL
);

CREATE TABLE INSTRUMENT (
    INSTRUMENT_ID NUMBER PRIMARY KEY,
    TICKER VARCHAR2(20),
    INSTRUMENT_NAME VARCHAR2(200) NOT NULL,
    INSTRUMENT_TYPE VARCHAR2(30) NOT NULL,
    ASSET_CLASS VARCHAR2(30) NOT NULL,
    ISSUER_ID NUMBER,
    CURRENCY VARCHAR2(3) NOT NULL,
    MATURITY_DATE DATE,
    COUPON_RATE NUMBER(8,4),
    NOMINAL_VALUE NUMBER(18,2),
    IS_ACTIVE NUMBER(1) NOT NULL,

    CONSTRAINT FK_INSTRUMENT_ISSUER
        FOREIGN KEY (ISSUER_ID)
            REFERENCES PARTY(PARTY_ID)
);

CREATE TABLE TX_TRANSACTION (
    TXN_ID NUMBER PRIMARY KEY,
    TXN_DATE DATE NOT NULL,
    TXN_TYPE VARCHAR2(20) NOT NULL,
    QUANTITY NUMBER(18,6),
    PRICE NUMBER(18,8),
    AMOUNT NUMBER(18,2) NOT NULL,
    CURRENCY VARCHAR2(3) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    SETTLEMENT_DATE DATE,
    PORTFOLIO_ID NUMBER NOT NULL,
    INSTRUMENT_ID NUMBER,
    COUNTERPARTY_ID NUMBER,
    CREATED_AT TIMESTAMP NOT NULL,

    CONSTRAINT FK_TXN_INSTRUMENT
        FOREIGN KEY (INSTRUMENT_ID)
            REFERENCES INSTRUMENT(INSTRUMENT_ID),

    CONSTRAINT FK_TXN_COUNTERPARTY
        FOREIGN KEY (COUNTERPARTY_ID)
            REFERENCES PARTY(PARTY_ID)
);